ai_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", landing_page, name="landing_page"),  # Landing page route
    path("home/", home, name="home"),  # Home page route after login/signup
    path('signup/', signup_view, name='signup'),
    path('parent-signup/', parent_signup, name='parent_signup'),
    path('school-signup/', school_signup_view, name='school_signup'),  # Added school-specific sign-up route
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('contact/', contact_view, name='contact'),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/add-class/', add_class, name='add_class'),
    path('dashboard/join-class/', join_class, name='join_class'),
    path('dashboard/course/<str:room_code>/', course_page, name='course_page'),
    path('dashboard/course/<str:room_code>//download/<int:file_id>/', download_syllabus, name='download_syllabus'),
    path('dashboard/course/<str:room_code>/preview-syllabus/<int:file_id>/', preview_syllabus, name='preview_syllabus'),
    path('dashboard/course/<str:room_code>/students-enrolled/', students_enrolled, name='students_enrolled'),
    path('dashboard/course/<str:room_code>/messages/', messages_list, name='messages_list'),
    path('dashboard/course/<str:room_code>/assignments-list/', assignments_list, name='assignments_list'),
    path('dashboard/course/<str:room_code>/assignments-list/delete-assignment/<int:assignment_id>/', delete_assignment, name='delete_assignment'),
    path('dashboard/course/<str:room_code>/assignments-list/edit-assignment/<int:pk>/', EditAssignment.as_view(), name='edit_assignment'),
    path('dashboard/course/<str:room_code>/assignment/<int:assignment_id>/questions/', AssignmentQuestionsListView.as_view(), name='assignment_questions'),
    path('dashboard/course/<str:room_code>/assignment/<int:assignment_id>/question/<int:question_id>/choices/edit', EditQuestionChoicesView.as_view(), name='edit_question_choices'),
    path('dashboard/course/<str:room_code>/assignments-list/<int:assignment_id>/submissions', SubmissionsListView.as_view(), name='assignment_submissions'),
    path('dashboard/course/<str:room_code>/assignments-list/<int:assignment_id>/submission/<int:pk>', StudentSubmissionDetailView.as_view(), name='student_submission_detail'),
    path('dashboard/course/<str:room_code>/assignment/<int:assignment_id>/', assignment_page, name='assignment_page'),
    path('classroom/<str:room_code>/assignment/create/', assignment_create, name='assignment_create'),
    path('dashboard/course/<str:room_code>/assignment/add-category/', add_category, name='add_category'),
    path('assignment/<int:pk>/', assignment_detail, name='assignment_detail'),
    path('classroom/<str:room_code>/assignment/<int:assignment_id>/question/create/', question_create, name='question_create'),
    path('dashboard/course/<str:room_code>/messages/create-message/', create_message, name='create_message'),
    path('dashboard/course/<str:room_code>/messages/<int:message_id>/delete', delete_message, name='delete_message'),
    path('dashboard/course/<str:room_code>/grades/', grades_list, name='grades_list'),
    path('dashboard/course/<str:room_code>/upload/', file_upload_view, name='file_upload'),
    path('dashboard/course/<str:room_code>/files/', file_list_view, name='file_list'),
    path('dashboard/course/<str:room_code>/edit/<int:file_id>/', file_edit_view, name='file_edit'),
    path('dashboard/course/<str:room_code>/download/<int:file_id>/', file_download_view, name='file_download'),
    path('dashboard/course/<str:room_code>/<str:display_name>/', file_preview_view, name='file_preview'),
    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/image-upload/<str:code>/', university_logo_upload_view, name='university_logo_upload'),
    path('admin-dashboard/display-logo/<str:code>/', display_logo, name='display_logo'),
    path('dashboard/profile-image-upload/', profile_image_upload_view, name='profile_image_upload'),
    ]

ai_education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ai_app.urls")),  # Include your app URLs
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# Serve static files (if needed)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ai_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django_quill.fields import QuillField 
import random
import string

class CourseMaterial(models.Model):
    professor = models.ForeignKey(User, on_delete=models.CASCADE)
    course_name = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='uploads/', null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    classroom = models.ForeignKey('ClassRoom', on_delete=models.CASCADE)
    display_name = models.CharField(max_length=255, null=True, blank=True)
    category=models.CharField(max_length=255, null=True, blank=True)
    visible_to_students = models.BooleanField(default=False)  
    is_syllabus = models.BooleanField(default=False)  # New column to handle syllabus marking

    def __str__(self):
        return self.display_name if self.display_name else self.file.name

class University(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=50, unique=True)  # Unique university code
    logo = models.ImageField(upload_to='university_logos/')
    primary_color = models.CharField(max_length=7, default='#00274C')
    secondary_color = models.CharField(max_length=7, default='#FFCB05')
    font_family = models.CharField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return self.name

class ClassRoom(models.Model):
    room_name = models.CharField(max_length=255)
    room_code = models.CharField(max_length=50, unique=True)
    room_password = models.CharField(max_length=100)
    description = models.TextField(blank=True) 
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='classes_teaching')
    students = models.ManyToManyField(User, related_name='enrolled_classrooms', blank=True)  
    room_number = models.CharField(max_length=10)
    class_times = models.JSONField(blank=True, null=True)

    def __str__(self):
        return self.room_name

class SchoolUserProfile(models.Model):
    STUDENT = 'student'
    TEACHER = 'teacher'
    ADMIN = 'admin'
    PARENT = 'parent'
    ROLE_CHOICES = [
        (STUDENT, 'Student'),
        (TEACHER, 'Teacher'),
        (ADMIN, 'Admin'),
        (PARENT, 'Parent'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    classes = models.ManyToManyField(ClassRoom, related_name='school_profiles', blank=True)  # Updated related_name to avoid conflict
    students = models.ManyToManyField('self', related_name='parents', symmetrical=False, blank=True, limit_choices_to={'role': 'student'})

    def __str__(self):
        return f"{self.user.username} - {self.role}"


class PairingCode(models.Model):
    code = models.CharField(max_length=10, unique=True)
    student = models.OneToOneField('SchoolUserProfile', on_delete=models.CASCADE, related_name='pairing_code', limit_choices_to={'role': 'student'})

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = self.generate_unique_code()
        super().save(*args, **kwargs)

    def generate_unique_code(self):
        while True:
            # Generate a random 10-character code consisting of uppercase letters and digits
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
            if not PairingCode.objects.filter(code=code).exists():
                return code

    def __str__(self):
        return f"Pairing Code for {self.student.user.username}: {self.code}"
    
class Category(models.Model):
    points = models.CharField(max_length=20)
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name='classrooms')
    category_name = models.CharField(max_length=255)

    def __str__(self):
        return self.category_name
    
class Assignments(models.Model):
    title = models.CharField(max_length=255)
    description = QuillField()
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    points = models.IntegerField(default=0, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='categories')
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name='classroom_assignments')
    time_limit = models.PositiveIntegerField(default=60)
    attempts = models.PositiveIntegerField(default=1)
    def __str__(self):
        return self.title

class Questions(models.Model):
    assignment = models.ForeignKey(Assignments, on_delete=models.CASCADE, related_name='assignment_questions')
    points = models.FloatField()
    QUESTION_TYPES = [
        ('MULTIPLE_CHOICE', 'Multiple Choice'),
        ('SHORT_ANSWER', 'Short Answer'),
        ('DROPDOWN', 'Dropdown')
    ]
    question_type = models.CharField(max_length=20, choices=QUESTION_TYPES)
    question = QuillField()

    def __str__(self):
        return self.question

class Choices(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE, related_name='question_choices')
    choice_text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.question

class StudentAnswers(models.Model):
    student_profile = models.ForeignKey(SchoolUserProfile, on_delete=models.CASCADE, related_name='student_answers')
    question = models.ForeignKey(Questions, on_delete=models.CASCADE, related_name='question_answers')
    choice = models.ForeignKey(Choices, on_delete=models.SET_NULL, null=True, blank=True)
    short_answer = models.TextField(null=True, blank=True)
    points_earned = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f"{self.student_profile.user.username} - {self.question}"

class Submissions(models.Model):
    student_profile = models.ForeignKey(SchoolUserProfile, on_delete=models.CASCADE, related_name='student_submission')
    assignment = models.ForeignKey(Assignments, on_delete=models.CASCADE, related_name='submission_answers')
    submitted_at = models.DateTimeField(null=True, blank=True)  # Field to store when the assignment is submitted
    start_time = models.DateTimeField(null=True, blank=True)  # New field to store the start time

    def __str__(self):
        return f"{self.student_profile.user.username} - {self.assignment.title} - {self.submitted_at}"
    
class Grades(models.Model):
    student_profile = models.ForeignKey(SchoolUserProfile, on_delete=models.CASCADE, related_name='student_grades')
    assignment = models.ForeignKey(Assignments, on_delete=models.CASCADE, related_name='assignment_grades')
    submission = models.ForeignKey(Submissions, on_delete=models.CASCADE, related_name='submission_grades')
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name='classroom_grades')  # New ForeignKey
    grade_value = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    feedback = models.TextField(null=True, blank=True)
    graded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student_profile.user.username} - {self.assignment.title} - Grade: {self.grade_value}"

class Messages(models.Model):
    title = models.CharField(max_length=255)
    text = QuillField()
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name='messages')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    
    def __str__(self):
        return self.title
    

ai_app/views/admin_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from ai_app.forms import UniversityLogoUploadForm
from ai_app.models import University, SchoolUserProfile
from django.contrib.auth import logout

@login_required
def admin_dashboard(request):
    profile = get_object_or_404(SchoolUserProfile, user=request.user, role='admin')
    university = profile.university
    profile_image = profile.profile_image
    return render(request, 'ai_app/dashboards/admin/admin_dashboard.html', {
        'university': university,
        'profile_image': profile_image
    })

@login_required
def university_logo_upload_view(request, code):
    profile = get_object_or_404(SchoolUserProfile, user=request.user)
    university = get_object_or_404(University, code=code)
    if request.method == 'POST':
        form = UniversityLogoUploadForm(request.POST, request.FILES, instance=university)
        if form.is_valid():
            image = form.save(commit=False)
            image.university = university
            image.save()
            return redirect('admin_dashboard')
    else:
        form = UniversityLogoUploadForm(instance=university)
    
    return render(request, 'ai_app/dashboards/admin/image_upload.html', {
        'form': form, 
        'university': university
    })

@login_required
def display_logo(request, code):
    profile = get_object_or_404(SchoolUserProfile, user=request.user)
    university = profile.university
    return {
        'university': university
    }

def logout_view(request):
    logout(request)
    return redirect('/')

ai_app/views/other_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from ai_app.forms import ProfileImageUploadForm
from ai_app.models import SchoolUserProfile
def home(request):
    return render(request, 'ai_app/main/home.html')

def landing_page(request):
    return render(request, 'ai_app/main/landingpage.html')

def contact_view(request):
    return render(request, 'ai_app/contact.html')

@login_required
def profile_image_upload_view(request):
    profile = get_object_or_404(SchoolUserProfile, user=request.user)
    if request.method == 'POST':
        form = ProfileImageUploadForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            # Redirect based on the user's role
            if profile.role == 'admin':
                return redirect('admin_dashboard')
            elif profile.role == 'teacher':
                return redirect('dashboard')
            elif profile.role == 'student':
                return redirect('dashboard')    
    else:
        form = ProfileImageUploadForm(instance=profile)
    
    return render(request, 'ai_app/dashboards/profile_image_upload.html', {
        'form': form
    })

ai_app/templates/ai_app/dashboards/teacher/files/file_edit.html
{% extends 'ai_app/dashboards/teacher/course_base.html' %}

{% block title %}
    Edit File
{% endblock %}

{% block header %}
    Edit File
{% endblock %}

{% block extra_css %}
<style>
    body {
        color: #333;
        overflow-x: hidden; /* Prevent horizontal scroll on the page */
    }

    .container {
        max-width: 93%;
        margin: 0 auto; /* Center the container */
        padding: 2rem;
        background-color: white;
        overflow: visible; /* Ensure no scrolling within the container */
    }

    .content-container {
        padding: 0;
    }

    .content-container h1 {
        text-align: center; /* Ensure h1 is centered */
        color: #333;
        font-size: 2rem;
        margin-top: 90px; /* Reduced margin for better layout */
        width: 100%; /* Make sure the h1 takes full width */
    }

    form {
        display: block;
        width: 100%; /* Ensure form takes full width */
    }

    label {
        margin-bottom: 0.5rem;
        font-weight: bold;
        display: block;
        color: #333;
        text-align: left;
        width: 100%;
    }

    input, textarea, select {
        padding: 0.8rem;
        margin-bottom: 1.5rem;
        border: 1px solid #ccc;
        border-radius: 8px;
        font-size: 1rem;
        width: 100%; /* Make inputs take full width */
        box-sizing: border-box;
    }

    /* Align checkboxes to the left */
    input[type="checkbox"] {
        width: auto; /* Prevent checkbox from being full-width */
        margin-right: 0.5rem;
    }

    .checkbox-label {
        display: flex;
        align-items: center;
        margin-bottom: 1.5rem;
    }

    button {
        padding: 1rem;
        background-color: var(--primary-color);
        color: var(--secondary-color);
        border: none;
        border-radius: 8px;
        cursor: pointer;
        transition: background-color 0.3s ease;
        margin-top: 10px;
        width: 100%; /* Button takes full width */
    }

    button:hover {
        background-color: #2f2f2f;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <!-- File field, hide the clear checkbox -->
        <label for="id_file">Upload File:</label>
        {{ form.file }}
        
        <!-- Display name -->
        <label for="id_display_name">Display Name:</label>
        {{ form.display_name }}

        <!-- Select Category -->
        <label for="id_category">Select Category:</label>
        {{ form.category }}

        <!-- Add New Category -->
        <label for="id_new_category">Add New Category:</label>
        {{ form.new_category }}

        <!-- Visible to Students checkbox -->
        <div class="checkbox-label">
            {{ form.visible_to_students }} 
            <label for="id_visible_to_students">Visible to Students</label>
        </div>

        <!-- Is Syllabus checkbox -->
        <div class="checkbox-label">
            {{ form.is_syllabus }} 
            <label for="id_is_syllabus">Is Syllabus</label>
        </div>

        <!-- Submit Button -->
        <button type="submit">Save Changes</button>
    </form>
</div>
{% endblock %}

ai_app/templates/ai_app/dashboards/teacher/files/file_list.html
{% extends 'ai_app/dashboards/teacher/course_base.html' %}

{% block title %}
{{ classroom.room_name }} - Uploaded Files
{% endblock %}

{% block header %}
    {{ classroom.room_name }} - Files
{% endblock %}

{% block extra_css %}
<style>
    .upload-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        color: #434443;
    }

    .upload-button {
        background-color: var(--primary-color);
        border-radius: 4px;
        padding: 8px;
    }

    .upload-button a {
        text-decoration: none;
        font-size: 16px;
        color: var(--secondary-color);
    }

    .upload-button:hover {
        filter: brightness(1.5);
    }

    /* Style the list of files */
    ul {
        list-style: none;
        padding: 0;
    }

    ul li {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px;
        margin-bottom: 10px;
        background-color: #f9f9f9;
        border-radius: 5px;
        border: 1px solid #e0e0e0;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    ul li a {
        text-decoration: none;
        font-weight: bold;
        color: var(--primary-color);
    }

    /* Buttons styling */
    .file-actions {
        display: flex;
        gap: 10px;
    }

    .file-actions a {
        padding: 5px 10px;
        border-radius: 5px;
        text-decoration: none;
        font-weight: bold;
    }

    .download-btn {
        color: var(--primary-color);
    }

    .download-btn:hover {
        filter: brightness(1.5);
    }

    .edit-btn {
        color: var(--primary-color)
    }

    .edit-btn:hover {
        filter: brightness(1.5);
    }

    /* Category headers */
    .category-header {
        font-size: 1.5rem;
        margin-top: 20px;
        font-weight: bold;
        color: #333;
    }

    .list-group-item {
        color: #434443;
    }
</style>
{% endblock %}

{% block content %}
<div class="upload-header">
    {% if user_role == 'teacher' %}
    <div class="upload-button">
        <a href="{% url 'file_upload' classroom.room_code %}">
            Upload File <i class="fa-solid fa-upload" style="font-size: 16px; margin-left: 5px;"></i></a>
    </div>
    {% endif %}
</div>

{% if files_by_category %}
    {% for category, files in files_by_category.items %}
    <h3 class="category-header">{{ category }}</h3>
    <ul>
        {% for file in files %}
        <li>
            <!-- File name on the left -->
            <span>
                {% if file.display_name and file.display_name != file.file.name %}
                <a href="{% url 'file_preview' classroom.room_code file.display_name %}" target="_blank">{{ file.display_name }}</a>
                {% else %}
                <a href="{% url 'file_preview' classroom.room_code file.file.name %}" target="_blank">{{ file.file.name }}</a>
                {% endif %}
            </span>

            <!-- Actions on the right: Download and Edit buttons -->
            <div class="file-actions">
                <!-- Indicate visibility status -->
                {% if user_role == 'teacher' %}
                {% if file.visible_to_students %}
                <a style="color:green;"><i class="fa-solid fa-eye"></i></a>
                {% else %}
                <a style="color:red;"><i class="fa-solid fa-eye-slash"></i></a>
                {% endif %}
                <!-- Edit Icon -->
                <a href="{% url 'file_edit' classroom.room_code file.id %}" class="edit-btn"><i class="fa-solid fa-pen-to-square"></i></a>
                {% endif %}
                <!-- Download Icon -->
                <a href="{% url 'file_download' classroom.room_code file.id %}" class="download-btn"><i class="fa-solid fa-download"></i></a>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% endfor %}
{% else %}
<p class="list-group-item text-center">No files uploaded yet.</p>
{% endif %}
{% endblock %}

ai_app/templates/ai_app/dashboards/teacher/files/file_preview.html
<h2>File: {{ file.display_name }}</h2>
<div class="download">
    <a href="{% url 'file_download' classroom.room_code file.id %}" class="download-btn"><i
            class="fa-solid fa-download"></i></a>
</div>
<img src="{{ file.file.url }}" alt="{{ file.file.name }}">

ai_app/templates/ai_app/dashboards/teacher/files/file_upload.html
{% extends 'ai_app/dashboards/teacher/course_base.html' %}

{% block title %}
    Upload File
{% endblock %}

{% block header %}
    Upload File
{% endblock %}

{% block extra_css %}
<style>
    :root {
        --font-family: '{{ font_family }}', sans-serif;
    }
    body {
        background-color: #f4f7f9;
        color: #434443;
    }

    .container {
        max-width: auto;
        margin: auto; /* Center the container */
        padding: 1rem;
        background-color: white;
        border-radius: 10px;
        box-shadow: 0 8px 8px rgba(0, 0, 0, 0.1);
        margin-left: -24px;
    }

    .header {
        display: cover;
    }

    h1 {
        text-align: center; /* Ensure h1 is centered */
        margin-bottom: 20px;
        padding-top: 20px;
        color: #333;
        font-size: 2rem;
        width: 100%; /* Make sure the h1 takes full width */
    }

    form {
        display: block;
        width: 100%; /* Ensure form takes full width */
    }

    label {
        margin-bottom: 0.5rem;
        font-weight: bold;
        display: block;
        text-align: left;
        width: 100%;
    }

    input, textarea, select {
        padding: 0.8rem;
        margin-bottom: 1.5rem;
        border: 1px solid #ccc;
        border-radius: 8px;
        font-size: 1rem;
        width: 100%; /* Make inputs take full width */
        box-sizing: border-box;
    }

    /* Align checkboxes to the left */
    input[type="checkbox"] {
        width: auto; /* Prevent checkbox from being full-width */
        margin-right: 0.5rem;
    }

    .checkbox-label {
        display: flex;
        align-items: center;
        margin-bottom: 1.5rem;
    }

    button {
        padding: 1rem;
        background-color: var(--primary-color);
        color: var(--secondary-color);
        border: none;
        border-radius: 8px;
        cursor: pointer;
        transition: background-color 0.3s ease;
        margin-top: 10px;
        width: 100%; /* Button takes full width */
    }

    button:hover {
        filter: brightness(1.5);
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_file">Upload File:</label>
        {{ form.file }}
        <label for="id_display_name">Display Name:</label>
        {{ form.display_name }}

        <label for="id_category">Select Category:</label>
        {{ form.category }}

        <label for="id_new_category">Add New Category:</label>
        {{ form.new_category }}

        <div class="checkbox-label">
            <input type="checkbox" id="id_visible_to_students" name="visible_to_students">
            <label for="id_visible_to_students">Visible to Students</label>
        </div>

        <div class="checkbox-label">
            <input type="checkbox" id="id_is_syllabus" name="is_syllabus">
            <label for="id_is_syllabus">Is Syllabus</label>
        </div>
        <button type="submit">Upload File</button>
    </form>
</div>
{% endblock %}