ai_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", landing_page, name="landing_page"),  # Landing page route
    path("home/", home, name="home"),  # Home page route after login/signup
    path('signup/', signup_view, name='signup'),
    path('parent-signup/', parent_signup, name='parent_signup'),
    path('school-signup/', school_signup_view, name='school_signup'),  # Added school-specific sign-up route
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('contact/', contact_view, name='contact'),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/add-class/', add_class, name='add_class'),
    path('dashboard/join-class/', join_class, name='join_class'),
    path('dashboard/course/<str:room_code>/', course_page, name='course_page'),
    path('dashboard/course/<str:room_code>//download/<int:file_id>/', download_syllabus, name='download_syllabus'),
    path('dashboard/course/<str:room_code>/preview-syllabus/<int:file_id>/', preview_syllabus, name='preview_syllabus'),
    path('dashboard/course/<str:room_code>/students-enrolled/', students_enrolled, name='students_enrolled'),
    path('dashboard/course/<str:room_code>/messages/', messages_list, name='messages_list'),
    path('dashboard/course/<str:room_code>/assignments-list/', assignments_list, name='assignments_list'),
    path('dashboard/course/<str:room_code>/assignments-list/delete-assignment/<int:assignment_id>/', delete_assignment, name='delete_assignment'),
    path('dashboard/course/<str:room_code>/assignments-list/edit-assignment/<int:pk>/', EditAssignment.as_view(), name='edit_assignment'),
    path('dashboard/course/<str:room_code>/assignment/<int:assignment_id>/questions/', AssignmentQuestionsListView.as_view(), name='assignment_questions'),
    path('dashboard/course/<str:room_code>/assignment/<int:assignment_id>/question/<int:question_id>/choices/edit', EditQuestionChoicesView.as_view(), name='edit_question_choices'),
    path('dashboard/course/<str:room_code>/assignments-list/<int:assignment_id>/submissions', SubmissionsListView.as_view(), name='assignment_submissions'),
    path('dashboard/course/<str:room_code>/assignments-list/<int:assignment_id>/submission/<int:pk>', StudentSubmissionDetailView.as_view(), name='student_submission_detail'),
    path('dashboard/course/<str:room_code>/assignment/<int:assignment_id>/', assignment_page, name='assignment_page'),
    path('classroom/<str:room_code>/assignment/create/', assignment_create, name='assignment_create'),
    path('dashboard/course/<str:room_code>/assignment/add-category/', add_category, name='add_category'),
    path('assignment/<int:pk>/', assignment_detail, name='assignment_detail'),
    path('classroom/<str:room_code>/assignment/<int:assignment_id>/question/create/', question_create, name='question_create'),
    path('dashboard/course/<str:room_code>/messages/create-message/', create_message, name='create_message'),
    path('dashboard/course/<str:room_code>/messages/<int:message_id>/delete', delete_message, name='delete_message'),
    path('dashboard/course/<str:room_code>/grades/', grades_list, name='grades_list'),
    path('dashboard/course/<str:room_code>/upload/', file_upload_view, name='file_upload'),
    path('dashboard/course/<str:room_code>/files/', file_list_view, name='file_list'),
    path('dashboard/course/<str:room_code>/edit/<int:file_id>/', file_edit_view, name='file_edit'),
    path('dashboard/course/<str:room_code>/download/<int:file_id>/', file_download_view, name='file_download'),
    path('dashboard/course/<str:room_code>/<str:display_name>/', file_preview_view, name='file_preview'),
    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/image-upload/<str:code>/', university_logo_upload_view, name='university_logo_upload'),
    path('admin-dashboard/display-logo/<str:code>/', display_logo, name='display_logo'),
    path('dashboard/profile-image-upload/', profile_image_upload_view, name='profile_image_upload'),
    ]

ai_education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ai_app.urls")),  # Include your app URLs
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# Serve static files (if needed)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ai_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django_quill.fields import QuillField 
import random
import string

class CourseMaterial(models.Model):
    professor = models.ForeignKey(User, on_delete=models.CASCADE)
    course_name = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='uploads/', null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    classroom = models.ForeignKey('ClassRoom', on_delete=models.CASCADE)
    display_name = models.CharField(max_length=255, null=True, blank=True)
    category=models.CharField(max_length=255, null=True, blank=True)
    visible_to_students = models.BooleanField(default=False)  
    is_syllabus = models.BooleanField(default=False)  # New column to handle syllabus marking

    def __str__(self):
        return self.display_name if self.display_name else self.file.name

class University(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=50, unique=True)  # Unique university code
    logo = models.ImageField(upload_to='university_logos/')
    primary_color = models.CharField(max_length=7, default='#00274C')
    secondary_color = models.CharField(max_length=7, default='#FFCB05')
    font_family = models.CharField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return self.name

class ClassRoom(models.Model):
    room_name = models.CharField(max_length=255)
    room_code = models.CharField(max_length=50, unique=True)
    room_password = models.CharField(max_length=100)
    description = models.TextField(blank=True) 
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='classes_teaching')
    students = models.ManyToManyField(User, related_name='enrolled_classrooms', blank=True)  
    room_number = models.CharField(max_length=10)
    class_times = models.JSONField(blank=True, null=True)

    def __str__(self):
        return self.room_name

class SchoolUserProfile(models.Model):
    STUDENT = 'student'
    TEACHER = 'teacher'
    ADMIN = 'admin'
    PARENT = 'parent'
    ROLE_CHOICES = [
        (STUDENT, 'Student'),
        (TEACHER, 'Teacher'),
        (ADMIN, 'Admin'),
        (PARENT, 'Parent'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    classes = models.ManyToManyField(ClassRoom, related_name='school_profiles', blank=True)  # Updated related_name to avoid conflict
    students = models.ManyToManyField('self', related_name='parents', symmetrical=False, blank=True, limit_choices_to={'role': 'student'})

    def __str__(self):
        return f"{self.user.username} - {self.role}"


class PairingCode(models.Model):
    code = models.CharField(max_length=10, unique=True)
    student = models.OneToOneField('SchoolUserProfile', on_delete=models.CASCADE, related_name='pairing_code', limit_choices_to={'role': 'student'})

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = self.generate_unique_code()
        super().save(*args, **kwargs)

    def generate_unique_code(self):
        while True:
            # Generate a random 10-character code consisting of uppercase letters and digits
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
            if not PairingCode.objects.filter(code=code).exists():
                return code

    def __str__(self):
        return f"Pairing Code for {self.student.user.username}: {self.code}"
    
class Category(models.Model):
    points = models.CharField(max_length=20)
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name='classrooms')
    category_name = models.CharField(max_length=255)

    def __str__(self):
        return self.category_name
    
class Assignments(models.Model):
    title = models.CharField(max_length=255)
    description = QuillField()
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    points = models.IntegerField(default=0, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='categories')
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name='classroom_assignments')
    time_limit = models.PositiveIntegerField(default=60)
    attempts = models.PositiveIntegerField(default=1)
    def __str__(self):
        return self.title

class Questions(models.Model):
    assignment = models.ForeignKey(Assignments, on_delete=models.CASCADE, related_name='assignment_questions')
    points = models.FloatField()
    QUESTION_TYPES = [
        ('MULTIPLE_CHOICE', 'Multiple Choice'),
        ('SHORT_ANSWER', 'Short Answer'),
        ('DROPDOWN', 'Dropdown')
    ]
    question_type = models.CharField(max_length=20, choices=QUESTION_TYPES)
    question = QuillField()

    def __str__(self):
        return self.question

class Choices(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE, related_name='question_choices')
    choice_text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.question

class StudentAnswers(models.Model):
    student_profile = models.ForeignKey(SchoolUserProfile, on_delete=models.CASCADE, related_name='student_answers')
    question = models.ForeignKey(Questions, on_delete=models.CASCADE, related_name='question_answers')
    choice = models.ForeignKey(Choices, on_delete=models.SET_NULL, null=True, blank=True)
    short_answer = models.TextField(null=True, blank=True)
    points_earned = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f"{self.student_profile.user.username} - {self.question}"

class Submissions(models.Model):
    student_profile = models.ForeignKey(SchoolUserProfile, on_delete=models.CASCADE, related_name='student_submission')
    assignment = models.ForeignKey(Assignments, on_delete=models.CASCADE, related_name='submission_answers')
    submitted_at = models.DateTimeField(null=True, blank=True)  # Field to store when the assignment is submitted
    start_time = models.DateTimeField(null=True, blank=True)  # New field to store the start time

    def __str__(self):
        return f"{self.student_profile.user.username} - {self.assignment.title} - {self.submitted_at}"
    
class Grades(models.Model):
    student_profile = models.ForeignKey(SchoolUserProfile, on_delete=models.CASCADE, related_name='student_grades')
    assignment = models.ForeignKey(Assignments, on_delete=models.CASCADE, related_name='assignment_grades')
    submission = models.ForeignKey(Submissions, on_delete=models.CASCADE, related_name='submission_grades')
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name='classroom_grades')  # New ForeignKey
    grade_value = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    feedback = models.TextField(null=True, blank=True)
    graded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student_profile.user.username} - {self.assignment.title} - Grade: {self.grade_value}"

class Messages(models.Model):
    title = models.CharField(max_length=255)
    text = QuillField()
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name='messages')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    
    def __str__(self):
        return self.title
    

ai_app/views/admin_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from ai_app.forms import UniversityLogoUploadForm
from ai_app.models import University, SchoolUserProfile
from django.contrib.auth import logout

@login_required
def admin_dashboard(request):
    profile = get_object_or_404(SchoolUserProfile, user=request.user, role='admin')
    university = profile.university
    profile_image = profile.profile_image
    return render(request, 'ai_app/dashboards/admin/admin_dashboard.html', {
        'university': university,
        'profile_image': profile_image
    })

@login_required
def university_logo_upload_view(request, code):
    profile = get_object_or_404(SchoolUserProfile, user=request.user)
    university = get_object_or_404(University, code=code)
    if request.method == 'POST':
        form = UniversityLogoUploadForm(request.POST, request.FILES, instance=university)
        if form.is_valid():
            image = form.save(commit=False)
            image.university = university
            image.save()
            return redirect('admin_dashboard')
    else:
        form = UniversityLogoUploadForm(instance=university)
    
    return render(request, 'ai_app/dashboards/admin/image_upload.html', {
        'form': form, 
        'university': university
    })

@login_required
def display_logo(request, code):
    profile = get_object_or_404(SchoolUserProfile, user=request.user)
    university = profile.university
    return {
        'university': university
    }

def logout_view(request):
    logout(request)
    return redirect('/')

ai_app/views/other_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from ai_app.forms import ProfileImageUploadForm
from ai_app.models import SchoolUserProfile
def home(request):
    return render(request, 'ai_app/main/home.html')

def landing_page(request):
    return render(request, 'ai_app/main/landingpage.html')

def contact_view(request):
    return render(request, 'ai_app/contact.html')

@login_required
def profile_image_upload_view(request):
    profile = get_object_or_404(SchoolUserProfile, user=request.user)
    if request.method == 'POST':
        form = ProfileImageUploadForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            # Redirect based on the user's role
            if profile.role == 'admin':
                return redirect('admin_dashboard')
            elif profile.role == 'teacher':
                return redirect('dashboard')
            elif profile.role == 'student':
                return redirect('dashboard')    
    else:
        form = ProfileImageUploadForm(instance=profile)
    
    return render(request, 'ai_app/dashboards/profile_image_upload.html', {
        'form': form
    })

ai_app/templates/ai_app/dashboards/teacher/assignment_detail.html
{% extends 'ai_app/dashboards/teacher/course_base.html' %}
{% block title %}
{{ assignment.title }}
{% endblock %}

{% block header %}
{{ assignment.title }}
{% endblock %}

{% block extra_css %}

<style>
    :root {
        --primary-color: var(--primary-color);
        --secondary-color: var(--secondary-color);
    }

    body {
        color: #434443;
    }

    .title {
        font-weight: bold;
        margin-bottom: 10px;
    }

    .text {
        font-weight: bold;
    }

    /* General button styles */
    button {
        background-color: var(--primary-color);
        color: var(--secondary-color);
        border: none;
        border-radius: 4px;
        padding: 8px 12px;
        font-size: 16px;
    }

    button:hover {
        filter: brightness(1.5);
        cursor: pointer;
    }

    .post-button {
        margin-top: 10px;
        /* Larger size for the "Add Question" button */
        padding: 12px 16px;
        font-size: 18px;
    }

    .choice-form {
        padding: 10px;
    }

    #choice-formset {
        margin-top: 20px;
    }

    .add-choice-button {
        /* Inherits styles from the general button */
    }

    /* Choice line styles */
    .choice-line {
        display: flex;
        align-items: center;
    }

    .choice-line input[type="text"] {
        flex-grow: 1;
        margin-right: 10px;
        padding: 8px;
        font-size: 16px;
        width: 50%;
    }

    .choice-line label {
        margin-right: 10px;
    }

    /* Remove Choice Button Styles */
    .remove-choice {
        background: none;
        color: #ff0000;
        /* Optional: Set a color for the trash icon */
        font-size: 16px;
        /* Increase the size of the icon */
        border: none;
        padding: 0;
        cursor: pointer;
    }

    .remove-choice:hover {
        filter: brightness(1.2);
    }

    /* Adjust icon size inside the button */
    .remove-choice i {
        font-size: 20px;
    }

    /* Error message styles */
    .error-message {
        color: #a94442;
        /* Red text */
        /* Light red background */
        /* Red border */

    }

    .field-error {
        border-color: #a94442;
        /* Red border for the input field */
    }

    .errorlist {
        list-style-type: none;
        padding: 0;
        margin: 0;
    }

    .errorlist li {
        color: #a94442;
        background-color: rgba(254, 176, 189, 1);
        border: 1px solid #a94442;
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 4px;

    }
</style>
{% endblock %}

{% block content %}
<h2>Description</h2>
<p>{{ assignment.description.html|safe }}</p>

<h2>Questions</h2>
<ol>
    {% for question in questions %}
        <li>({{ question.get_question_type_display }}){{ question.question.html|safe }} </li>
        {% for choice in question.question_choices.all %}
            <p><small>{{choice.choice_text}}</p></small>
        {% endfor %}
    {% endfor %}
</ol>

<h2>Add a New Question</h2>
<form method="post">
    {{ form.media }}
    {% csrf_token %}
    {{ form.as_p }}

    <div id="choice-formset" style="display:none;">
        <h3>Choices</h3>
        {{ formset.management_form }}
        <div id="formset-forms">
            {% for form in formset %}
            <div class="choice-form" style="display:none;">
                <div class="choice-line">
                    {{ form.choice_text.errors }}
                    {{ form.choice_text }}
                    {{ form.is_correct }}
                    <label for="{{ form.is_correct.id_for_label }}">Correct</label>
                    <button type="button" class="remove-choice"><i class="fa-solid fa-trash"></i></button>
                </div>
            </div>
            {% endfor %}
        </div>
        <button type="button" class="add-choice-button" id="add-choice">Add Choice</button>
    </div>

    <button type="submit" class="post-button">Add Question</button>
</form>

<!-- Empty form template for cloning -->
<div id="empty-form" style="display:none;">
    <div class="choice-form">
        <div class="choice-line">
            {{ formset.empty_form.choice_text.errors }}
            {{ formset.empty_form.choice_text }}
            {{ formset.empty_form.is_correct }}
            <label for="{{ formset.empty_form.is_correct.id_for_label }}">Correct</label>
            <input type="checkbox" name="__prefix__-DELETE" id="id___prefix__-DELETE" style="display:none;">
            <button type="button" class="remove-choice"><i class="fa-solid fa-trash"></i></button>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        var questionTypeField = $('#id_question_type');
        var choiceFormset = $('#choice-formset');
        var totalForms = $('#id_form-TOTAL_FORMS');
        var formContainer = $('#formset-forms');

        function toggleChoiceFormset() {
            var questionType = questionTypeField.val();
            if (questionType == 'MULTIPLE_CHOICE' || questionType == 'DROPDOWN') {
                choiceFormset.show();
                $('.choice-form').show();
            } else {
                choiceFormset.hide();
                $('.choice-form').hide();
            }
        }

        toggleChoiceFormset();

        questionTypeField.change(function () {
            toggleChoiceFormset();
        });

        var formIdx = parseInt(totalForms.val());
        $('#add-choice').click(function () {
            var emptyFormHtml = $('#empty-form').html();
            var newFormHtml = emptyFormHtml.replace(/__prefix__/g, formIdx);
            formContainer.append(newFormHtml);
            formIdx++;
            totalForms.val(formIdx);
        });

        $(document).on('click', '.remove-choice', function () {
            var $form = $(this).closest('.choice-form');
            // Mark the form for deletion
            $form.find('input[type="checkbox"][name$="-DELETE"]').prop('checked', true);
            $form.hide();
        });
    });
</script>
{% endblock %}

ai_app/templates/ai_app/dashboards/teacher/assignment_page.html
{% extends 'ai_app/dashboards/teacher/course_base.html' %}

{% block title %}
{{ assignment.title }} - Assignment Page
{% endblock %}

{% block header %}
{{ assignment.title }}
{% endblock %}

{% block extra_css %}
<style>
    body {
        color: #434443;
    }

    .upload-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        color: #434443;
    }

    .upload-button {
        background-color: var(--primary-color);
        border-radius: 4px;
        padding: 8px;
    }

    .upload-button a {
        text-decoration: none;
        font-size: 16px;
        color: var(--secondary-color);
    }

    .upload-button:hover {
        filter: brightness(1.5);
    }
</style>

{% endblock %}

{% block content %}
<div class="upload-header">
    {% if user_role == 'student' %}
    <div class="upload-button">
        <a href="{}">Submit <i class="fa-solid fa-pen-to-square" style="font-size: 16px; margin-left: 5px;"></i></a>
    </div>
    {% endif %}
</div>
<div class="assignment-details">
    <p><strong>Start Date:</strong> {{ assignment.start_date }}</p>
    <p><strong>Due Date:</strong> {{ assignment.due_date }}</p>
    <p><strong>Points:</strong> {{ assignment.points }}</p>
    <p><strong>Description:</strong> {{ assignment.description.html|safe }}</p>
    <hr>
    {% for question in questions %}
    <p>
        <strong>Question {{ forloop.counter }}:
            <small style="font-weight: normal;">({{question.points |floatformat:0}} Points)</small>
        </strong> {{ question.question.html|safe }}
    </p>
    <ul>
        {% for choice in question.question_choices.all %}
        <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul>
    {% endfor %}

</div>
<div class="upload-header">
    <div class="upload-button">
        <a href="{}">Submit Assignment</a>
    </div>
</div>
{% endblock %}

ai_app/templates/ai_app/dashboards/teacher/course_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family={{ font_family|urlencode }}:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <script src="https://unpkg.com/htmx.org@2.0.2"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <style>
        :root {
            --font-family: '{{ font_family }}', sans-serif;
        }

        html,
        body {
            font-family: var(--font-family);
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            height: 100%;
        }

        /* Navbar at the top */
        .navbar {
            width: 100vw;
            height: 60px;
            background-color: var(--primary-color);
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0 20px;
            box-sizing: border-box;
            position: fixed;
            top: 0;
            left: 0;
            z-index: 1001;
            /* Ensure navbar stays on top */
        }

        /* Main container to hold sidebar and content */
        .container {
            display: flex;
            width: 100%;
            height: calc(100vh - 60px);
            /* Adjust based on navbar height */
            margin-top: 60px;
            /* Push content below the navbar */
        }

        /* Sidebar */
        .sidebar {
            width: 200px;
            background-color: #f9fafb;
            padding: 1rem;
            border-right: 1px solid #e0e0e0;
            height: calc(100vh - 60px);
            /* Adjust for the navbar height */
            position: fixed;
            top: 60px;
            /* Start below navbar */
            left: 0;
            overflow-y: auto;
            /* Scrollable if content overflows */
        }

        /* Content container */
        .content-container {
            flex-grow: 1;
            margin-left: 200px;
            /* Leave space for the sidebar */
            padding: 2rem;
            height: calc(100vh - 60px);
            /* Adjust for the navbar */
            box-sizing: border-box;
            overflow-y: auto;
            /* Scroll if content overflows */
            margin-top: -50px;
        }

        h1 {
            font-size: 2.5rem;
            color: #333;
            text-align: center;
            margin: 0;
            margin-top: 40px;
        }
    </style>

    {% block extra_css %}
    {% endblock %}
</head>

<body>
    <!-- Sidebar and Content -->
    <div class="container">
        <!-- Sidebar -->
        <div class="sidebar">
            {% block sidebar %}
            {% include 'includes/sidebar.html' %}
            {% endblock %}
        </div>

        <!-- Content -->
        <div class="content-container">
            <h1>{% block header %}{% endblock %}</h1>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>

</html>

ai_app/templates/ai_app/dashboards/teacher/create_message.html
{% extends 'ai_app/dashboards/teacher/course_base.html' %}

{% block title %}
    Create Message
{% endblock %}

{% block header %}
    Create a New Message
{% endblock %}

{% block extra_css %}
<style>
    body {
        color: #434443;
    }
    .title {
        font-weight: bold;
        margin-bottom: 10px;
    }

    .title input {
        width: 99%;
        height: 30px;
        font-size: 18px;
    }

    .text {
        font-weight: bold;
    }

    .post-button {
        background-color: var(--primary-color);
        border-radius: 4px;
        padding: 8px;
        color: var(--secondary-color);
        margin-top: 10px;
        font-size: 16px;
    }

    .post-button:hover {
        filter: brightness(1.5);
        cursor: pointer;
    }
</style>
    {{ form.media }}  
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="title">
            <label for="id_title">Title:</label>
            {{ form.title }}
        </div>
        
        <div> 
            <label for="id_text" class="text">Message:</label>
            {{ form.text }}  <!-- This will render the Quill editor -->
        </div>
        
        <button class="post-button" type="submit">Post Message</button>
    </form>
{% endblock %}

ai_app/templates/ai_app/dashboards/teacher/teacher_dashboard_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} My Website {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
</head>

<body>
    <header>
        <a href="{% url 'landing_page' %}">
            <img src="{% static 'images/logo.png' %}" alt="My Logo" class="logo">
        </a>
        <!-- Add navigation here -->
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>